- name: Create a folder in Windows VM
  hosts: all
  gather_facts: no
  tasks:
    - name: Create folder on Windows VM
      ansible.windows.win_file:
        path: "G:\\myfolder"
        state: directory
