---
- name: Start MSSQLSERVER Service
  hosts: all
  tasks:
    - name: Start MSSQLSERVER service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: started
      register: start_service_status

    - name: Display current MSSQLSERVER service status (after starting)
      ansible.windows.win_service_info:
        name: MSSQLSERVER
      register: service_status

    - name: Show the status of the MSSQLSERVER service after starting
      debug:
        var: service_status
