---
- name: Start MSSQLSERVER Service
  hosts: all
  tasks:
    - name: Start MSSQLSERVER service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: started
      register: start_service_result

    - name: Display the result of starting MSSQLSERVER service
      debug:
        msg: "Result of starting MSSQLSERVER service: {{ start_service_result }}"
