---
- name: Stop MSSQLSERVER Service
  hosts: all
  tasks:
    - name: Stop MSSQLSERVER service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: stopped
      register: stop_service_status

    - name: Display current MSSQLSERVER service status (after stopping)
      ansible.windows.win_service_info:
        name: MSSQLSERVER
      register: service_status

    - name: Show the status of the MSSQLSERVER service after stopping
      debug:
        var: service_status
