---
- name: Stop MSSQLSERVER Service
  hosts: all
  tasks:
    - name: Stop MSSQLSERVER service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: stopped
        force: yes
      register: stop_service_result

    - name: Display the result of stopping MSSQLSERVER service
      debug:
        msg: "{{ stop_service_result }}"
