---
- name: Check MSSQLSERVER Service status
  hosts: all
  tasks:
    - name: Get the service status
      ansible.windows.win_service_info:
        name: MSSQLSERVER
      register: service_status

    - name: Display the service status
      debug:
        msg: "MSSQLSERVER service status: {{ service_status }}"
